M48
; DRILL file KiCad 10.0.3 date 2026-09-20T23:16:09
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-20T23:16:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.4966Y-3.6798
X5.6575Y-3.5189
T2
X4.1262Y-3.6342
X4.2445Y-3.7525
M30
